import { WaitlistSignup } from './supabase';

// Dummy data for demo purposes - timestamps spread across last 1-2 weeks
const baseDate = new Date('2026-06-23T12:00:00Z');

export const dummySignups: WaitlistSignup[] = [
  {
    id: '1',
    email: 'sarah.chen@techstartup.io',
    message_type_focus: 'Work',
    referral_intent: 'Yes',
    use_case_tags: ['Difficult feedback', 'Team or leadership comms'],
    blockers: ["Don't know how it'll be received", 'Tone always comes out wrong'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: '2',
    email: 'marcus.johnson@gmail.com',
    message_type_focus: 'Personal',
    referral_intent: 'Maybe',
    use_case_tags: ['Dating or personal messages', 'Other'],
    blockers: ['Anxious about sending it'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: '3',
    email: 'elena.rodriguez@enterprise.com',
    message_type_focus: 'Work',
    referral_intent: 'Yes',
    use_case_tags: ['Team or leadership comms', 'Customer support replies'],
    blockers: ["Don't know how it'll be received", 'Takes too long to get right'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: '4',
    email: 'david.kim@consulting.co',
    message_type_focus: 'Both equally',
    referral_intent: 'Yes',
    use_case_tags: ['Difficult feedback', 'Sales or pitch messages', 'Team or leadership comms'],
    blockers: ["Don't know how it'll be received"],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: '5',
    email: 'priya.sharma@startup.vc',
    message_type_focus: 'Work',
    referral_intent: 'Yes',
    use_case_tags: ['Sales or pitch messages', 'Team or leadership comms'],
    blockers: ['Tone always comes out wrong', 'Takes too long to get right'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: '6',
    email: 'james.wilson@pm.me',
    message_type_focus: 'Work',
    referral_intent: 'Maybe',
    use_case_tags: ['Team or leadership comms'],
    blockers: ['Anxious about sending it', "Don't know how it'll be received"],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: '7',
    email: 'amanda.foster@design.co',
    message_type_focus: 'Both equally',
    referral_intent: 'Yes',
    use_case_tags: ['Difficult feedback', 'Dating or personal messages'],
    blockers: ['Tone always comes out wrong'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 28).toISOString(),
  },
  {
    id: '8',
    email: 'ryan.chen@engineering.io',
    message_type_focus: 'Work',
    referral_intent: 'No',
    use_case_tags: ['Difficult feedback'],
    blockers: ["Don't know how it'll be received", 'Anxious about sending it'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 36).toISOString(),
  },
  {
    id: '9',
    email: 'lisa.thompson@healthcare.org',
    message_type_focus: 'Work',
    referral_intent: 'Maybe',
    use_case_tags: ['Customer support replies', 'Team or leadership comms'],
    blockers: ['Takes too long to get right'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: '10',
    email: 'michael.brown@finance.com',
    message_type_focus: 'Work',
    referral_intent: 'Yes',
    use_case_tags: ['Sales or pitch messages', 'Difficult feedback'],
    blockers: ["Don't know how it'll be received", 'Tone always comes out wrong', 'Anxious about sending it'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 52).toISOString(),
  },
  {
    id: '11',
    email: 'nina.patel@agency.creative',
    message_type_focus: 'Both equally',
    referral_intent: 'Yes',
    use_case_tags: ['Sales or pitch messages', 'Team or leadership comms', 'Dating or personal messages'],
    blockers: ['Tone always comes out wrong'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 60).toISOString(),
  },
  {
    id: '12',
    email: 'tom.garcia@retail.co',
    message_type_focus: 'Work',
    referral_intent: 'Maybe',
    use_case_tags: ['Customer support replies'],
    blockers: ["Don't know how it'll be received"],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: '13',
    email: 'sophie.martin@edu.university',
    message_type_focus: 'Both equally',
    referral_intent: 'Yes',
    use_case_tags: ['Difficult feedback', 'Team or leadership comms'],
    blockers: ['Takes too long to get right', 'Anxious about sending it'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 80).toISOString(),
  },
  {
    id: '14',
    email: 'alex.turner@freelance.me',
    message_type_focus: 'Work',
    referral_intent: 'Yes',
    use_case_tags: ['Sales or pitch messages', 'Customer support replies'],
    blockers: ["Don't know how it'll be received", 'Tone always comes out wrong'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 88).toISOString(),
  },
  {
    id: '15',
    email: 'jessica.lee@nonprofit.org',
    message_type_focus: 'Work',
    referral_intent: 'Maybe',
    use_case_tags: ['Team or leadership comms', 'Difficult feedback'],
    blockers: ['Anxious about sending it'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 96).toISOString(),
  },
  {
    id: '16',
    email: 'chris.anderson@law.firm',
    message_type_focus: 'Work',
    referral_intent: 'No',
    use_case_tags: ['Difficult feedback'],
    blockers: ['Takes too long to get right'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 104).toISOString(),
  },
  {
    id: '17',
    email: 'taylor.morgan@tech.dev',
    message_type_focus: 'Personal',
    referral_intent: 'Yes',
    use_case_tags: ['Dating or personal messages', 'Other'],
    blockers: ["Don't know how it'll be received", 'Anxious about sending it'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 112).toISOString(),
  },
  {
    id: '18',
    email: 'jordan.white@marketing.agency',
    message_type_focus: 'Work',
    referral_intent: 'Yes',
    use_case_tags: ['Sales or pitch messages', 'Team or leadership comms'],
    blockers: ['Tone always comes out wrong'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 130).toISOString(),
  },
  {
    id: '19',
    email: 'casey.taylor@gaming.studio',
    message_type_focus: 'Not sure yet',
    referral_intent: 'Maybe',
    use_case_tags: ['Other'],
    blockers: ['Other'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 140).toISOString(),
  },
  {
    id: '20',
    email: 'riley.cooper@media.news',
    message_type_focus: 'Work',
    referral_intent: 'Yes',
    use_case_tags: ['Difficult feedback', 'Team or leadership comms'],
    blockers: ["Don't know how it'll be received", 'Takes too long to get right', 'Anxious about sending it'],
    created_at: new Date(baseDate.getTime() - 1000 * 60 * 60 * 150).toISOString(),
  },
];

export const SIGNUP_COUNT = 187;
export const TOTAL_SPOTS = 500;
